### ISSUE TITLE
Permitir múltiples conexiones a base de datos

### ISSUE THREAD

**Issue by mgalbis** [iti-ict/wakamiti#117]
Permitir que pueda haber más de una conexión a diferentes bases de datos, identificándolas por un nombre. Por ejemplo, mediante pasos:

```
Dada la URL de conexión a BBDD 'jdbc:h2:tcp://localhost:9092/~/TESTDB1' usando el usuario 'test' y la contraseña 'test', identificada por 'db-one'
Y la URL de conexión a BBDD 'jdbc:h2:tcp://localhost:9093/~/TESTDB2' usando el usuario 'test' y la contraseña 'test', identificada por 'db-two'
Cuando ...
Entonces usando la conexión 'db-two', varios usuarios con STATE = '1' existen en la tabla USER
```

O mediante la configuración yml, por ejemplo:

```yml
database:
  db-one:
     connection:
       url: jdbc:h2:tcp://localhost:9092/~/test1
       username: test
       password: test
  db-two:
     connection:
       url: jdbc:h2:tcp://localhost:9093/~/test2
       username: test
       password: test
```
