### ISSUE TITLE
Report extra info

### ISSUE THREAD

**Issue by mgalbis** [iti-ict/wakamiti#255]
Include extra project information via yaml that appears in the test report. E.g:
```yaml
wakamiti:
  extra:
    version: 1.3
    other_data: Something
```
